parameters:
#    gl_notification.example.class: GL\NotificationBundle\Example

services:
#    gl_notification.example:
#        class: %gl_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#    gl_notification:
#        class: 'GL\NotificationBundle\DependencyInjection\CoreNotification'
#        arguments: [ @annotation_reader, @snc_redis.default, @security.context ]
#
#
#    gl_notification.grouphandler.entity:
#       class: 'GL\NotificationBundle\GroupHandler\Entity'
#       arguments: [ @doctrine.orm.entity_manager ]

    gl.notification_manager:
        class: 'GL\NotificationBundle\Lib\Notifications'
        arguments: [ @service_container ]

    gl.notification.storage.redis:
        class: 'GL\NotificationBundle\Storage\RedisStorage'
        arguments: [ @service_container ]

    gl.notification.storage.doctrine:
        class: 'GL\NotificationBundle\Storage\DoctrineStorage'
        arguments: [ @service_container ]


